OnlineLearning/urls.py
from .views import HomeView, DashboardView
from django.conf.urls.static import static
from django.urls import include, path
from django.conf import settings
from . import views
from django.conf.urls import (handler400, handler403, handler404, handler500)

# handler404 = "OnlineLearning.views.page_not_found"

urlpatterns = [
    # path('', views.insert)
    path("", view=HomeView.as_view(), name='home'),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('dashboard/', DashboardView, name='dashboard'),
    path('teachers/', include('teachers.urls', namespace='teachers')),
    path('admins/', include('admins.urls', namespace='admins')),
    path('students/', include('students.urls', namespace='students')),

    # path('signup', views.signup, name="signup"),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    # if settings.DEBUG:

accounts/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static
from .views import IndexView,TeacherCreateView,StudentCreateView,LoginView,LogoutView


app_name = 'accounts'

urlpatterns = [
    # path('', IndexView.as_view(), name='signup'),
    path('login/', LoginView,name='login'),
    path('logout/', LogoutView, name='logout'),
    path('signup/student/', StudentCreateView, name='student_signup'),
    path('signup/teacher/', TeacherCreateView, name='teacher_signup'),

]
# urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

admins/urls.py
from django.urls import include, path
from .views import DashboardView,RolesView,RolesCreateView,RolesDeleteView,RolesEditView,RolesUpdateView
from . import views
app_name = 'admins'

urlpatterns = [
    path('', DashboardView, name='dashboard'),

    path('profile/edit', views.AccountUpdateView, name='edit_account'),

    path('user/update/<int:user_id>', views.UserUpdateView, name='edit_users'),
    path('user/delete/<int:user_id>/<int:check_user>', views.UserDeleteView, name='delete_users'),

    path('change_pass', views.ChangePasswordView, name='change_password'),

    path('search', views.SearchResultView, name='search'),

    path('roles/', RolesView, name='roles'),
    path('roles/add/', RolesCreateView, name='add_roles'),
    path('roles/delete/<int:id>', RolesDeleteView, name='delete_roles'),
    path('roles/edit/<int:id>', RolesEditView, name='edit_roles'),
    path('roles/update/<int:id>', RolesUpdateView, name='update_roles'),

    path('courses/', views.CourseView, name='courses'),
    path('courses/add', views.CourseCreateView, name='add_courses'),
    path('courses/update/<int:id>', views.CourseUpdateView, name='update_courses'),
    path('courses/delete/<int:id>', views.CourseDeleteView, name='delete_courses'),
    path('courses/all', views.CourseViewAll, name='view_all_courses'),

    path('students/', views.StudentView, name='student'),
    path('students/view/<int:id>', views.StudentDetailView, name='view_student'),
    path('students/view/payment/<int:course_id>/<int:id>', views.StudentPaymentDetailView, name='view_student_payment'),
    path('students/view_by_course/<int:course_id>', views.StudentByCourseView, name='view_student_by_course'),

    path('teachers/', views.TeacherView, name='teacher'),
    path('teacher/view/<int:id>', views.TeacherDetailView, name='view_teacher'),

    path('duration', views.DurationView, name='duration'),
    path('duration/add', views.DurationCreateView, name='add_duration'),
    path('duration/update/<int:id>', views.DurationUpdateView, name='update_duration'),
    path('duration/delete/<int:id>', views.DeleteDurationView, name='delete_duration'),
    path('duration/all', views.DurationViewAll, name='view_all_duration'),

    path('fees', views.FeesView, name='fees'),
    path('fees/add', views.FeesCreateView, name='add_fees'),
    path('fees/update/<int:id>', views.FeesUpdateView, name='update_fees'),
    path('fees/delete/<int:id>', views.FeesDeleteView, name='delete_fees'),
    path('fees/all', views.FeesViewAll, name='view_all_fees'),

    path('resources', views.ResourceView, name='resources'),
    path('resources/course/<int:courseId>', views.ResourceCourseView, name='course_resources'),
    path('resources/course/add/<int:courseId>', views.ResourceCourseCreateView, name='add_resources'),
    path('resources/course/update/<int:id>', views.ResourceCourseUpdateView, name='update_resources'),
    path('resources/course/delete/<int:id>', views.ResourceCourseDeleteView, name='delete_resource'),
    path('resources/all', views.ResourceViewAll, name='view_all_resources'),

    path('test', views.TestView, name='tests'),
    path('test/course/<int:courseId>', views.TestCourseView, name='course_tests'),
    path('test/course/add/<int:courseId>', views.TestQuestionCreateView, name='add_tests'),
    path('test/course/update/<int:id>', views.TestsCourseUpdateView, name='update_tests'),
    path('test/course/delete/<int:id>', views.TestCourseDeleteView, name='delete_tests'),
    path('tes/all', views.TestViewAll, name='view_all_tests'),

]

students/urls.py
from django.urls import include, path
from .views import DashboardView
from . import views


app_name = 'students'

urlpatterns = [
    path('', DashboardView, name='dashboard'),

    path('profile/edit', views.AccountUpdateView, name='edit_account'),

    path('courses', views.CoursesView, name='courses'),

    path('search', views.SearchResultView, name='search'),

    path('change_pass', views.ChangePasswordView, name='change_password'),

    path('course_detail/<int:id>', views.CourseDetailView, name='course_detail'),
    path('course_enroll/<int:id>', views.CourseEnrollView, name='course_enroll'),
    path('course_unroll/<int:id>', views.CourseUnrollView, name='course_unroll'),

    path('payments/<int:id>', views.PaymentView, name='payments'),

    path('tests', views.TestView, name='tests'),
    path('tests/<int:courseId>', views.CourseTestView, name='course_test'),

]

students/models.py
from django.db import models

# Create your models here.

students/forms.py
from django import forms

from accounts.models import Courses


class CourseForm(forms.ModelForm):
    class Meta:
        model = Courses
        # fields="__all__"
        exclude = ('user_id',)
        widgets = {
            'course_title': forms.TextInput(attrs={'class': 'form-control', "placeholder": ""}),
            'course_description': forms.Textarea(attrs={'class': 'form-control', "placeholder": ""}),
            # 'course_thumbnail': forms.ImageField(attrs={'class': 'form-control'})
        }

students/views.py
import os

from django.shortcuts import render, redirect
from accounts.models import Roles, Users, Courses, Duration, Resources, Enrolls, Tests, Fees, FeesPayment
from accounts.forms import UserEditForm, ChangePasswordForm
from django.contrib import messages
from OnlineLearning import views
from accounts.decorators import unauthenticated_user
from datetime import date
from django.db.models import Q
from django.contrib.auth.hashers import make_password, check_password
from PIL import Image
from django.shortcuts import get_object_or_404
today = date.today()

def check_img(filename):
    try:
        Image.open(filename)
        return True
    except IOError:
        return False


@unauthenticated_user
def DashboardView(request):
    return render(request, 'students/dashboard.html', views.ContextForStudents(request))


@unauthenticated_user
def AccountUpdateView(request):
    users = Users.objects.get(id=request.session['user_id'])
    form = UserEditForm(instance=users)
    if request.method == "POST":
        form = UserEditForm(request.POST, request.FILES, instance=users)
        if form.is_valid:
            try:
                form.save()
                messages.success(request, 'Your profile has been edited successfully.')
                return redirect('students:dashboard')
            except:
                pass

    return render(request, "students/edit_account.html", {'form': form, 'user': users})


@unauthenticated_user
def CourseDetailView(request, id):
    # try:
        courses = Courses.objects.get(id=id)
        duration = get_object_or_404(Duration, course_id=id)
        enrolls_total = Enrolls.objects.filter(course_id=id).count()
        fee = Fees.objects.get(course_id=courses)
        users = Users.objects.get(id=request.session['user_id'])
        is_paid = False
        check_paid = FeesPayment.objects.filter(course_id=courses, paid_from=users)
        if check_paid.exists():
            is_paid = True
        return render(request, "students/course_detail.html", {'courses': courses, 'duration': duration,
                                                                   'enrolls_total': enrolls_total, 'fees': fee,
                                                                   'user': users, 'is_paid': is_paid, })
    # except:
    #     pass



@unauthenticated_user
def CourseEnrollView(request, id):
    courses = Courses.objects.get(id=id)
    duration = Duration.objects.get(course_id=id)
    resource = Resources.objects.filter(course_id=id)
    fee = Fees.objects.get(course_id=id)
    user = Users.objects.get(id=request.session['user_id'])
    check_paid = FeesPayment.objects.filter(course_id=courses, paid_from=user)
    payment = []
    paid_fee = 0
    if check_paid.exists():
        for v in check_paid:
            payment.append(v)
    if len(payment) > 0:
        paid_fee = payment[0].paid_amount

    enrolls = Enrolls(
        course_id=courses,
        user_id=user,
        teacher_id=courses.user_id.id
    )
    payment_image = ''
    payment_mode = 'Card'

    if 'voucher_image' in request.FILES :
        payment_image = request.FILES['voucher_image']
        payment_mode = 'Bank account'
        if not check_img(payment_image):
            messages.error(request, 'The image is not supported.')
            return redirect('students:payments', id=id)

    price = fee.price

    feesPayment = FeesPayment(
        course_id=courses,
        paid_amount=price,
        payment_image=payment_image,
        payment_method=payment_mode,
        status=1,
        paid_from=user,
        paid_to=courses.user_id.id,
    )

    if request.method == "POST":

            new = Enrolls.objects.filter(course_id=courses, user_id=user)
            payments = FeesPayment.objects.filter(course_id=courses, paid_from=user)
            if new.exists():
                messages.error(request, 'Selected course already enrolled.')
                return redirect('students:course_detail', id=id)
            elif payments.exists() or fee.is_free:
                enrolls.save()
                messages.success(request, 'You have successfully enrolled this subject.')
            else:
                feesPayment.save()
                enrolls.save()
                messages.success(request, 'You have successfully enrolled this subject.')

    enrolls_total = Enrolls.objects.filter(course_id=id).count()
    return render(request, "students/course_enroll.html", {'courses': courses, 'duration': duration,
                                                           'resources': resource, 'enrolls_total': enrolls_total,
                                                           'fees': fee, 'user': user, "payment": paid_fee})


@unauthenticated_user
def CourseUnrollView(request, id):
    courses = Courses.objects.get(id=id)
    user = Users.objects.get(id=request.session['user_id'])
    enroll = Enrolls.objects.get(course_id=courses, user_id=user)
    enroll.delete()
    messages.success(request, 'Selected course remove from enroll.')
    return redirect("students:course_detail", id=id)


@unauthenticated_user
def CoursesView(request):
    return render(request, "students/courses.html", views.ContextForStudents(request))


@unauthenticated_user
def TestView(request):
    return render(request, "students/test.html", views.ContextForStudents(request))


@unauthenticated_user
def PaymentView(request, id):
    courses = Courses.objects.get(id=id)
    duration = Duration.objects.get(course_id=id)
    resource = Resources.objects.filter(course_id=id)
    fee = Fees.objects.get(course_id=id)
    enrolls_total = Enrolls.objects.filter(course_id=id).count()
    user = Users.objects.get(id=request.session['user_id'])
    context = {'courses': courses,
               'duration': duration,
               'resources': resource,
               'enrolls_total': enrolls_total,
               'fees': fee,
               'user': user}
    return render(request, "students/payment.html", context)


@unauthenticated_user
def CourseTestView(request, courseId):
    courses = Courses.objects.get(id=courseId)
    test = Tests.objects.filter(course_id=courseId)
    duration = Duration.objects.get(course_id=courseId)
    user = Users.objects.get(id=request.session['user_id'])
    check_paid = FeesPayment.objects.filter(course_id=courses, paid_from=user)
    payment = []
    paid_fee = 0
    if check_paid.exists():
        for v in check_paid:
            payment.append(v)
    if len(payment) > 0:
        paid_fee = payment[0].paid_amount

    if request.method == 'POST':
        questions = Tests.objects.filter(course_id=courseId)
        score = 0
        wrong = 0
        correct = 0
        total = 0
        for q in questions:
            total += 1
            if q.correct == request.POST.get(q.question):
                score += 10
                correct += 1
            else:
                wrong += 1
        percent = score / (total * 10) * 100
        context = {
            'score': score,
            'time': request.POST.get('timer'),
            'correct': correct,
            'wrong': wrong,
            'percent': percent,
            'total': total,
            'courses': courses,
            'tests': test,
            'user': user,
            'issue_date': today.strftime("%B %d, %Y"),
        }
        return render(request, 'students/certificate.html', context)
    else:
        questions = test
        enrolls_total = Enrolls.objects.filter(course_id=courseId).count()
        context = {'duration': duration, 'enrolls_total': enrolls_total, 'questions': questions, 'courses': courses,
                   'tests': test, 'user': user, "payment": paid_fee}

    return render(request, "students/course_test.html", context)


def SearchResultView(request):
    user = Users.objects.get(id=request.session['user_id'])

    if request.method == 'POST':
        search_text = request.POST.get('search')
        # course = Courses.objects.get(Q( title__icontains=search_text) & Q(content__icontains=search_text))

        courses = Courses.objects.filter(Q(course_title__icontains=search_text)
                                    | Q(code__icontains=search_text))
        fees = Fees.objects.all()

        fees_data = []
        for elem in courses:
            for v in fees:
                if v.course_id.id == elem.id:
                    fees_data.append(v)

    return render(request, "students/search_result.html", {"fees": fees_data,
                                                           "search_text": search_text,
                                                           "course_count": len(fees_data), 'user': user
                                                           })


def ChangePasswordView(request):
    user = Users.objects.get(id=request.session['user_id'])
    form = ChangePasswordForm()
    if request.method == 'POST':
        old_password = request.POST.get('old_password')
        new_password = request.POST.get('new_password')
        retype_password = request.POST.get('retype_password')
        check_pwd = check_password(old_password, user.password)

        if old_password == '' or new_password == '' or retype_password =='':
            messages.error(request, 'All fields are mandatory.')
        elif check_pwd == False:
            messages.error(request, 'Your entered password with old password doesn\'t match.')
        elif new_password != retype_password:
            messages.error(request, 'Your retype password is not match with new password.')
        else:
            user.password = make_password(new_password)
            user.save()
            messages.success(request, 'Your password is changed successfully.')
            redirect('students:dashboard')
    return render(request, "students/change_password.html", {"form": form,  'user': user})

students/templates/students/base.html
<!DOCTYPE html> {% load static %}
<html>

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no" />
    <title>{% block title %}Base{% endblock title %}</title>
    <link rel="stylesheet" href="{% static 'teachers/bootstrap/css/bootstrap.min.css' %}" />
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i" />
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=IM+Fell+Great+Primer+SC&amp;display=swap" />
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.12.0/css/all.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css" />
    <link rel="stylesheet" href="{% static 'teachers/fonts/fontawesome5-overrides.min.css' %}" />
    <style>

            .sidebar-dark {
                background-color: #19222D;
            }
           .navbar-light {
                background-color: #031F42;
            }
            .card{
            color:#f3f3ff;
            background-color: #031F42;
            border:none;
            }

            .card>img {
                 transition: transform .5s ease-in-out;
              transform-origin: 0 0;
              }
            #content,html{
            background-color:#020E1B;
            }

            .max-lines {
                display: -webkit-box;
                -webkit-line-clamp: 2;
                -webkit-box-orient: vertical;
                overflow: hidden;
                }
                li.active{
                background-color:#020E1B;
                }
        </style>
    {% block style %}

    <!-- Body Block : END -->
    {% endblock style %}
</head>

<body id="page-top">
    <div id="wrapper">
        <nav class="navbar navbar-dark  align-items-start sidebar sidebar-dark accordion  p-0 ">
            <div class="container-fluid d-flex flex-column p-0">
                <a class="navbar-brand d-flex justify-content-center align-items-center sidebar-brand m-0" href="{% url 'students:dashboard' %}">
                    <div class="sidebar-brand-icon"><i class="fa fa-dashcube"></i></div>
                    <div class="sidebar-brand-text mx-3"><span>STUDENT</span></div>

                </a>
                <hr class="sidebar-divider my-0" />
                <ul class="navbar-nav text-light" id="accordionSidebar">

                    <li class="nav-item">
                        <a class="nav-link active" href="{% url 'students:dashboard' %}"><i
                                                class="fas fa-inbox fa-sm fa-fw mr-2 text-gray-400"></i> <span>Dashboard</span></a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'students:courses' %}"><i
                                                class="fa fa-book fa-sm fa-fw mr-2 text-gray-400"></i> <span>Courses</span></a>
                    </li>
                     <li class="nav-item">
                        <a class="nav-link" href="{% url 'students:tests' %}"><i
                                                class="fa fa-graduation-cap fa-sm fa-fw mr-2 text-gray-400"></i> <span>Test</span></a>
                    </li>
<!--                     <li class="nav-item">-->
<!--                        <a class="nav-link" href=""><i-->
<!--                                                class="fa fa-file fa-sm fa-fw mr-2 text-gray-400"></i> <span>Results</span></a>-->
<!--                    </li>-->
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'accounts:logout' %}">
                           <i class="fas fa-sign-out-alt fa-sm fa-fw mr-2 text-gray-400"></i>
                            <span>Log out</span></a>
                    </li>

                </ul>
<!--                <div class="text-center my-auto d-none d-md-inline">-->
<!--                    <button class="btn rounded-circle border-0 btn-success" id="sidebarToggle" type="button"></button>-->
<!--                </div>-->
            </div>
        </nav>
        <div class="d-flex flex-column" id="content-wrapper">
            <div id="content">
                <nav class="navbar navbar-light navbar-expand shadow mb-4 topbar static-top">
                    <div class="container-fluid">
                        <button class="btn btn-link d-md-none rounded-circle mr-3" id="sidebarToggleTop" type="button">
                            <i class="fas fa-bars"></i>
                        </button>
                        <form class="form-inline d-none d-sm-inline-block mr-auto ml-md-3 my-2 my-md-0 mw-100 navbar-search" method="POST"  action="{% url 'students:search' %}">
                            {% csrf_token %}
                            <div class="input-group">
                                <input class="bg-light form-control border-0 small" type="text" name="search" placeholder="Enter a course code or course name ..." />
                                <div class="input-group-append">
                                    <button class="btn btn-primary py-0" type="submit">
                                        <i class="fas fa-search"></i>
                                    </button>
                                </div>
                            </div>
                        </form>
                        <ul class="navbar-nav flex-nowrap ml-auto">
                            <li class="nav-item dropdown d-sm-none no-arrow">
                                <a class="dropdown-toggle nav-link" aria-expanded="false" data-toggle="dropdown" href="#"><i class="fas fa-search"></i></a>
                                <div class="dropdown-menu dropdown-menu-right p-3 animated--grow-in" aria-labelledby="searchDropdown">
                                    <form class="form-inline mr-auto navbar-search w-100" method="POST"  action="{% url 'students:search' %}">
                                            {% csrf_token %}
                                            <div class="input-group">
                                            <input class="bg-light form-control border-0 small" type="text" name="search" placeholder="Enter a course code or course name ..." />
                                            <div class="input-group-append">
                                                <button class="btn btn-primary py-0" type="submit">
                                                    <i class="fas fa-search"></i>
                                                </button>
                                            </div>
                                        </div>
                                    </form>
                                </div>
                            </li>
                            <div class="d-none d-sm-block topbar-divider"></div>
                            <li class="nav-item dropdown no-arrow">
                                <div class="nav-item dropdown no-arrow">
                                    <a class="dropdown-toggle nav-link" aria-expanded="false" data-toggle="dropdown" href="#">
                                        <span class="d-none d-lg-inline mr-2 text-gray-600 small">
                                            {{user.name|upper}}
                                        </span>
                                        {% if user.profile_image %}
                                            <img class="rounded-circle border img-profile" src="{{user.profile_image.url}}"/>
                                         {% else %}
                                            <img class="rounded-circle border img-profile" src="{% static 'teachers/img/avatars/img.png' %}" />
                                        {% endif %}
                                    </a>
                                    <div class="dropdown-menu shadow dropdown-menu-right animated--grow-in">
                                        <a class="dropdown-item" href="{% url 'students:edit_account' %}"><i
                                                class="fas fa-user fa-sm fa-fw mr-2 text-gray-400"></i>&nbsp;Profile</a>
                                        <div class="dropdown-divider"></div>
                                        <a class="dropdown-item" href="{% url 'students:change_password' %}"><i
                                                class="fas fa-unlock-alt fa-sm fa-fw mr-2 text-gray-400"></i>Change Password</a>
                                        <div class="dropdown-divider"></div>
                                        <a class="dropdown-item" href="{% url 'accounts:logout' %}"><i
                                                class="fas fa-sign-out-alt fa-sm fa-fw mr-2 text-gray-400"></i>&nbsp;Logout</a>
                                    </div>
                                </div>
                            </li>
                        </ul>
                    </div>
                </nav>
                <div class="container-fluid mb-5">
                    <!-- Body Block : START -->
                    {% block content %}

                    <!-- Body Block : END -->
                    {% endblock content %}
                </div>

            </div>

        </div>
    </div>

    {% block script %}

    <!-- Body Block : END -->
    {% endblock script %}
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.6.1/js/bootstrap.bundle.min.js"></script>
<!--    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-easing/1.4.1/jquery.easing.js"></script>-->
    <script src="{% static 'teachers/js/theme.js' %}"></script>
    <script>
        $(document).ready(function() {
          $('li.active').removeClass('active').removeAttr('aria-current');
          $('a[href="' + location.pathname + '"]').closest('li').addClass('active').attr('aria-current', 'page');
        });
    </script>
</body>

</html>

students/templates/students/certificate.html
{% extends 'students/base.html' %} {% block title %}{{courses.course_title}}{% endblock title %} {% block content %}
{% load static %}
  {% block style %}
        <style>
            .certificate{
            background: url('{% static 'accounts/assets/img/certificate1.jpg' %}') no-repeat;
              width: 100%;
              height:650px;
              border: 1px solid;
              background-size:  100%  100%;
            }
            .certificate-body{
            height:100%;
            width: 100%;
            display:flex;
            justify-content:center;
            align-items:center;
            flex-direction:column;
            }
        </style>
    <!-- Body Block : END -->
    {% endblock style %}
<div >
    {% if messages %}
          {% for message in messages %}
            <div class="alert alert-dismissible {{ message.tags }} mt-3">
              <button type="button" class="close" data-dismiss="alert">
              ×
              </button>
              <strong>{{message}}</strong>
            </div>
         {% endfor %}
    {% endif %}

    <div class="row justify-content-left mt-4">
    <div class="col-lg-9">
        <div class="card shadow  card-body p-4 " style="background-color:#042339" >
            <h3 class="pt-2 text-gray-400 "><b>{{courses.course_title}}</b></h3>

            <p class="card-text text-gray-400 small">By: <span class="text-success">{{courses.user_id.name}}</span></p>
        </div>

         <div class="container ">
            <div class="card-columns" style="padding: 10px; margin: 20px;">
                <div class="card"  style="width: 32rem; border:5px black solid">
                    <img class="card-img-top" src="{% static 'accounts/assets/img/congratulations.png' %}" alt="Congratulations img">
                    <div class="card d-body pl-5" >
                        <h5 class="card-title">Score: {{score}}</h5>
                        <p class="card-text">Percentage: {{percent}}%</p>
                        <p class="card-text">Time Taken: {{time}} seconds</p>
                        <p class="card-text">Correct answers: {{correct}}</p>
                        <p class="card-text">Incorrect answers: {{wrong}}</p>
                        <p class="card-text">Total questions: {{total}}</p>
                        <h5>All the best for next test!</h5>
                    </div>
                </div>
            </div>
        </div>

        <div class=" certificate" style="">
           <div class="certificate-body">
                <h5 style="margin-top:130px; font-size:0.7rem;">{{user.name}}</h5>
               <h6 style="margin-top:50px; font-size:0.6rem;">{{courses.course_title}}</h6>
               <h6 style="margin-top:35px; font-size:0.7em;">{{percent}}%</h6>
               <h6  style="margin-top:80px;  font-size:0.7rem;">{{issue_date}}</h6>
           </div>
        </div>


    </div>


    <div class="col-lg-3 justify-content-center sidebar">
           <div class="card shadow  card-body p-2 " style="background-color:#042339" >
               {% if courses.course_thumbnail %}
                    <img  src="{{ courses.course_thumbnail.url }}" height="160" alt="teacher image">
                {%else%}
                    <img  src="https://images.pexels.com/photos/4498366/pexels-photo-4498366.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500" height="160" alt="teacher image">
               {% endif %}
                     <div class="card-body">
                           <h6 class="card-title text-success "><b><i class="fas fa-check text-success mr-3"></i> Rs 500 paid</b></h6>
                             <a href="{% url 'students:course_enroll' id=courses.id %}">
                             <form method="post"  action="{% url 'students:course_unroll' id=courses.id %}">
                                      {% csrf_token %}
                                      <button class="btn btn-primary py-0" type="submit">
                                   <h6 class="card-text small p-3">Unroll</h6>
                                 </button>
                             </form>
                              </a>
                         <hr>
                         <h6 class="card-text text-gray-400">This course includes</h6>
                         <hr>
                        <p class="card-text small font-weight-light text-gray-400"> <i class="fas fa-check text-success mr-3"></i> <span >Study materials</span></p>
                    </div>
            </div>
    </div>
</div>




{% endblock content %}