OnlineLearning/urls.py
from .views import HomeView, DashboardView
from django.conf.urls.static import static
from django.urls import include, path
from django.conf import settings
from . import views
from django.conf.urls import (handler400, handler403, handler404, handler500)

# handler404 = "OnlineLearning.views.page_not_found"

urlpatterns = [
    # path('', views.insert)
    path("", view=HomeView.as_view(), name='home'),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('dashboard/', DashboardView, name='dashboard'),
    path('teachers/', include('teachers.urls', namespace='teachers')),
    path('admins/', include('admins.urls', namespace='admins')),
    path('students/', include('students.urls', namespace='students')),

    # path('signup', views.signup, name="signup"),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    # if settings.DEBUG:

accounts/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static
from .views import IndexView,TeacherCreateView,StudentCreateView,LoginView,LogoutView


app_name = 'accounts'

urlpatterns = [
    # path('', IndexView.as_view(), name='signup'),
    path('login/', LoginView,name='login'),
    path('logout/', LogoutView, name='logout'),
    path('signup/student/', StudentCreateView, name='student_signup'),
    path('signup/teacher/', TeacherCreateView, name='teacher_signup'),

]
# urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

admins/urls.py
from django.urls import include, path
from .views import DashboardView,RolesView,RolesCreateView,RolesDeleteView,RolesEditView,RolesUpdateView
from . import views
app_name = 'admins'

urlpatterns = [
    path('', DashboardView, name='dashboard'),

    path('profile/edit', views.AccountUpdateView, name='edit_account'),

    path('user/update/<int:user_id>', views.UserUpdateView, name='edit_users'),
    path('user/delete/<int:user_id>/<int:check_user>', views.UserDeleteView, name='delete_users'),

    path('change_pass', views.ChangePasswordView, name='change_password'),

    path('search', views.SearchResultView, name='search'),

    path('roles/', RolesView, name='roles'),
    path('roles/add/', RolesCreateView, name='add_roles'),
    path('roles/delete/<int:id>', RolesDeleteView, name='delete_roles'),
    path('roles/edit/<int:id>', RolesEditView, name='edit_roles'),
    path('roles/update/<int:id>', RolesUpdateView, name='update_roles'),

    path('courses/', views.CourseView, name='courses'),
    path('courses/add', views.CourseCreateView, name='add_courses'),
    path('courses/update/<int:id>', views.CourseUpdateView, name='update_courses'),
    path('courses/delete/<int:id>', views.CourseDeleteView, name='delete_courses'),
    path('courses/all', views.CourseViewAll, name='view_all_courses'),

    path('students/', views.StudentView, name='student'),
    path('students/view/<int:id>', views.StudentDetailView, name='view_student'),
    path('students/view/payment/<int:course_id>/<int:id>', views.StudentPaymentDetailView, name='view_student_payment'),
    path('students/view_by_course/<int:course_id>', views.StudentByCourseView, name='view_student_by_course'),

    path('teachers/', views.TeacherView, name='teacher'),
    path('teacher/view/<int:id>', views.TeacherDetailView, name='view_teacher'),

    path('duration', views.DurationView, name='duration'),
    path('duration/add', views.DurationCreateView, name='add_duration'),
    path('duration/update/<int:id>', views.DurationUpdateView, name='update_duration'),
    path('duration/delete/<int:id>', views.DeleteDurationView, name='delete_duration'),
    path('duration/all', views.DurationViewAll, name='view_all_duration'),

    path('fees', views.FeesView, name='fees'),
    path('fees/add', views.FeesCreateView, name='add_fees'),
    path('fees/update/<int:id>', views.FeesUpdateView, name='update_fees'),
    path('fees/delete/<int:id>', views.FeesDeleteView, name='delete_fees'),
    path('fees/all', views.FeesViewAll, name='view_all_fees'),

    path('resources', views.ResourceView, name='resources'),
    path('resources/course/<int:courseId>', views.ResourceCourseView, name='course_resources'),
    path('resources/course/add/<int:courseId>', views.ResourceCourseCreateView, name='add_resources'),
    path('resources/course/update/<int:id>', views.ResourceCourseUpdateView, name='update_resources'),
    path('resources/course/delete/<int:id>', views.ResourceCourseDeleteView, name='delete_resource'),
    path('resources/all', views.ResourceViewAll, name='view_all_resources'),

    path('test', views.TestView, name='tests'),
    path('test/course/<int:courseId>', views.TestCourseView, name='course_tests'),
    path('test/course/add/<int:courseId>', views.TestQuestionCreateView, name='add_tests'),
    path('test/course/update/<int:id>', views.TestsCourseUpdateView, name='update_tests'),
    path('test/course/delete/<int:id>', views.TestCourseDeleteView, name='delete_tests'),
    path('tes/all', views.TestViewAll, name='view_all_tests'),

]

OnlineLearning/views.py
from django.shortcuts import redirect, render
from django.views.generic import TemplateView, CreateView, ListView
from django.contrib.auth.decorators import login_required, user_passes_test
from accounts.models import Roles, Users, Courses, Enrolls, Fees, FeesPayment
from django.template import RequestContext

class HomeView(TemplateView):
    template_name = "onlineLearning/home.html"

@login_required
def DashboardView(request):
    # return redirect('teachers:dashboard')
    if request.user.is_student:
        return redirect('students:dashboard')
    if request.user.is_teacher:
        return redirect('teachers:dashboard')
    if request.user.is_superuser:
        return redirect('admins:dashboard')


# for sharing data to all html pages
def AllContextItems(request):
    user = Users.objects.get(id=request.session['user_id'])
    users_count = Users.objects.all().count()
    students_count = Users.objects.filter(user_role_id=request.session['roles_std']).values_list('name', flat=True).count()
    teachers_count = Users.objects.filter(user_role_id=request.session['roles_teacher']).values_list('name', flat=True).count()
    courses_count = Courses.objects.all().count()
    courses_of_admins = Courses.objects.filter(user_id=user)     # course created by admins and teachers
    fees_paid = FeesPayment.objects.filter(paid_to=user.id)
    enroll_students = Enrolls.objects.filter(teacher_id=user.id)

    labels = ["Students", "Teachers", "Courses"]
    data = [students_count, teachers_count, courses_count]

    # for city in students_count:
    #     labels.append(city.name)
    # data.append(students_count)
    # data.append(teachers_count)

    context = {
        'users_count': users_count-1,
        'students_count': students_count,
        'enroll_count': enroll_students.count(),
        'teachers_count': teachers_count,
        'courses_count': courses_count,
        'user': user,
        'courses_of_admins': courses_of_admins,
        'fees_paid_count': fees_paid.count(),
        'labels': labels,
        'data': data,
    }
    return context


def ContextForStudents(request):
    userId=request.session['user_id']
    user = Users.objects.get(id=userId)
    teachers_count = Users.objects.filter(user_role_id=request.session['roles_teacher']).values_list('name', flat=True).count()
    all_courses = Courses.objects.all()
    courses_count = Courses.objects.all().count()
    enrolls = Enrolls.objects.filter(user_id=userId)
    fees_paid = FeesPayment.objects.filter(paid_from=user)
    fees = Fees.objects.all()

    fees_data = []
    for elem in all_courses:
        for v in fees:
            if v.course_id.id == elem.id:
                fees_data.append(v)

    context = {
        'user': user,
        'teacher_count': teachers_count,
        'course_count': fees.count(),
        #only courses are shown who has fees
        'fee_paid_count': fees_paid.count(),
        'all_courses': all_courses,
        'enrolls': enrolls,
        'enroll_count': enrolls.count(),
        'fees': fees_data

    }

    return context


def page_not_found_view(request, exception):
    return render(request, '403.html', status=404)

# views.py
def handler404(request, exception):
    context = RequestContext(request)
    err_code = 404
    response = render_to_response('404.html', {"code":err_code}, context)
    response.status_code = 404
    return response

OnlineLearning/templates/onlineLearning/home.html
<!DOCTYPE html> {% load static %}
<html>

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no" />
    <title>{% block title %}Online Learning{% endblock title %}</title>
    <link rel="stylesheet" href="{% static 'accounts/assets/bootstrap/css/bootstrap.min.css' %}" />
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800" />
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Merriweather:400,300,300italic,400italic,700,700italic,900,900italic" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/aos/2.3.4/aos.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/baguettebox.js/1.10.0/baguetteBox.min.css" />
</head>

<body id="page-top" data-bs-spy="scroll" data-bs-target="#mainNav" data-bs-offset="57">

    <nav class="navbar navbar-light navbar-expand-lg fixed-top mt-2" id="mainNav">
        <div class="container">
            <a class="navbar-brand" href="{% url 'home' %}">Online Learning</a><button data-bs-toggle="collapse" data-bs-target="#navbarResponsive" class="navbar-toggler navbar-toggler-right" type="button" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                <i class="fa fa-align-justify"></i>
            </button>
            <div class="collapse navbar-collapse" id="navbarResponsive">
                <ul class="navbar-nav ms-auto">
                     <li class="nav-item">
                        <a class="nav-link" href="{% url 'accounts:teacher_signup' %}">Become an instructor</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'accounts:login' %}">Login</a>
                    </li>
                    <li class="nav-item">
                        <a  class="nav-link btn btn-primary btn-sm" role="button" href="{% url 'accounts:student_signup' %}">Sign up</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>

    <header class="text-center text-white d-flex masthead" style=" background-image: url('{% static 'accounts/assets/img/header-backimg2.jpg' %}');">
        <!-- start -->
        {% block content %}
        <div class="container my-auto">
            <div class="row">
                <div class="col-lg-10 mx-auto">
                     <hr />
                    <h1 class="text-uppercase">
                        <strong style="background-color:#212529; padding:0px;">Get started with <br />the online learning system</strong>
                    </h1>
                    <hr />

                </div>
            </div>
            <div class="col-lg-8 mx-auto">
                <p class="text-faded mb-5"></p>
                <a class="btn btn-primary btn-xl" role="button" href="{% url 'accounts:login' %}">Get Started</a>
            </div>
        </div>
        <!-- end -->
        {% endblock content %}
    </header>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
    <script src="{% static 'accounts/assets/js/bs-init.js' %}"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/aos/2.3.4/aos.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/baguettebox.js/1.10.0/baguetteBox.min.js"></script>
    <script src="{% static 'accounts/assets/js/creative.js' %}"></script>
</body>

</html>

OnlineLearning/templates/onlineLearning/navbar.html
<nav class="navbar navbar-light navbar-expand-lg fixed-top" id="mainNav">
        <div class="container">
            <a class="navbar-brand" href="{% url 'home' %}">Online Learning</a><button data-bs-toggle="collapse" data-bs-target="#navbarResponsive" class="navbar-toggler navbar-toggler-right" type="button" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                <i class="fa fa-align-justify"></i>
            </button>
            <div class="collapse navbar-collapse" id="navbarResponsive">
                <ul class="navbar-nav ms-auto">
                     <li class="nav-item">
                        <a class="nav-link" href="{% url 'accounts:teacher_signup' %}">Become an instructor</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'accounts:login' %}">Login</a>
                    </li>
                    <li class="nav-item">
                        <a  class="nav-link btn btn-primary btn-sm" role="button" href="{% url 'accounts:student_signup' %}">Sign up</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>