OnlineLearning/urls.py
from .views import HomeView, DashboardView
from django.conf.urls.static import static
from django.urls import include, path
from django.conf import settings
from . import views
from django.conf.urls import (handler400, handler403, handler404, handler500)

# handler404 = "OnlineLearning.views.page_not_found"

urlpatterns = [
    # path('', views.insert)
    path("", view=HomeView.as_view(), name='home'),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('dashboard/', DashboardView, name='dashboard'),
    path('teachers/', include('teachers.urls', namespace='teachers')),
    path('admins/', include('admins.urls', namespace='admins')),
    path('students/', include('students.urls', namespace='students')),

    # path('signup', views.signup, name="signup"),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    # if settings.DEBUG:

accounts/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static
from .views import IndexView,TeacherCreateView,StudentCreateView,LoginView,LogoutView


app_name = 'accounts'

urlpatterns = [
    # path('', IndexView.as_view(), name='signup'),
    path('login/', LoginView,name='login'),
    path('logout/', LogoutView, name='logout'),
    path('signup/student/', StudentCreateView, name='student_signup'),
    path('signup/teacher/', TeacherCreateView, name='teacher_signup'),

]
# urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

admins/urls.py
from django.urls import include, path
from .views import DashboardView,RolesView,RolesCreateView,RolesDeleteView,RolesEditView,RolesUpdateView
from . import views
app_name = 'admins'

urlpatterns = [
    path('', DashboardView, name='dashboard'),

    path('profile/edit', views.AccountUpdateView, name='edit_account'),

    path('user/update/<int:user_id>', views.UserUpdateView, name='edit_users'),
    path('user/delete/<int:user_id>/<int:check_user>', views.UserDeleteView, name='delete_users'),

    path('change_pass', views.ChangePasswordView, name='change_password'),

    path('search', views.SearchResultView, name='search'),

    path('roles/', RolesView, name='roles'),
    path('roles/add/', RolesCreateView, name='add_roles'),
    path('roles/delete/<int:id>', RolesDeleteView, name='delete_roles'),
    path('roles/edit/<int:id>', RolesEditView, name='edit_roles'),
    path('roles/update/<int:id>', RolesUpdateView, name='update_roles'),

    path('courses/', views.CourseView, name='courses'),
    path('courses/add', views.CourseCreateView, name='add_courses'),
    path('courses/update/<int:id>', views.CourseUpdateView, name='update_courses'),
    path('courses/delete/<int:id>', views.CourseDeleteView, name='delete_courses'),
    path('courses/all', views.CourseViewAll, name='view_all_courses'),

    path('students/', views.StudentView, name='student'),
    path('students/view/<int:id>', views.StudentDetailView, name='view_student'),
    path('students/view/payment/<int:course_id>/<int:id>', views.StudentPaymentDetailView, name='view_student_payment'),
    path('students/view_by_course/<int:course_id>', views.StudentByCourseView, name='view_student_by_course'),

    path('teachers/', views.TeacherView, name='teacher'),
    path('teacher/view/<int:id>', views.TeacherDetailView, name='view_teacher'),

    path('duration', views.DurationView, name='duration'),
    path('duration/add', views.DurationCreateView, name='add_duration'),
    path('duration/update/<int:id>', views.DurationUpdateView, name='update_duration'),
    path('duration/delete/<int:id>', views.DeleteDurationView, name='delete_duration'),
    path('duration/all', views.DurationViewAll, name='view_all_duration'),

    path('fees', views.FeesView, name='fees'),
    path('fees/add', views.FeesCreateView, name='add_fees'),
    path('fees/update/<int:id>', views.FeesUpdateView, name='update_fees'),
    path('fees/delete/<int:id>', views.FeesDeleteView, name='delete_fees'),
    path('fees/all', views.FeesViewAll, name='view_all_fees'),

    path('resources', views.ResourceView, name='resources'),
    path('resources/course/<int:courseId>', views.ResourceCourseView, name='course_resources'),
    path('resources/course/add/<int:courseId>', views.ResourceCourseCreateView, name='add_resources'),
    path('resources/course/update/<int:id>', views.ResourceCourseUpdateView, name='update_resources'),
    path('resources/course/delete/<int:id>', views.ResourceCourseDeleteView, name='delete_resource'),
    path('resources/all', views.ResourceViewAll, name='view_all_resources'),

    path('test', views.TestView, name='tests'),
    path('test/course/<int:courseId>', views.TestCourseView, name='course_tests'),
    path('test/course/add/<int:courseId>', views.TestQuestionCreateView, name='add_tests'),
    path('test/course/update/<int:id>', views.TestsCourseUpdateView, name='update_tests'),
    path('test/course/delete/<int:id>', views.TestCourseDeleteView, name='delete_tests'),
    path('tes/all', views.TestViewAll, name='view_all_tests'),

]

students/urls.py
from django.urls import include, path
from .views import DashboardView
from . import views


app_name = 'students'

urlpatterns = [
    path('', DashboardView, name='dashboard'),

    path('profile/edit', views.AccountUpdateView, name='edit_account'),

    path('courses', views.CoursesView, name='courses'),

    path('search', views.SearchResultView, name='search'),

    path('change_pass', views.ChangePasswordView, name='change_password'),

    path('course_detail/<int:id>', views.CourseDetailView, name='course_detail'),
    path('course_enroll/<int:id>', views.CourseEnrollView, name='course_enroll'),
    path('course_unroll/<int:id>', views.CourseUnrollView, name='course_unroll'),

    path('payments/<int:id>', views.PaymentView, name='payments'),

    path('tests', views.TestView, name='tests'),
    path('tests/<int:courseId>', views.CourseTestView, name='course_test'),

]

teachers/urls.py
from django.conf.urls.static import static
from django.urls import include, path
from django.conf import settings
from .views import DashboardView
from . import views

app_name = 'teachers'

urlpatterns = [
    path('', DashboardView, name='dashboard'),

    path('profile/edit', views.AccountUpdateView, name='edit_account'),
    path('change_pass', views.ChangePasswordView, name='change_password'),

    path('search', views.SearchResultView, name='search'),

    path('students', views.StudentView, name='students'),
    path('students/view/<int:id>', views.StudentDetailView, name='view_student'),
    path('students/view/payment/<int:course_id>/<int:id>', views.StudentPaymentDetailView, name='view_student_payment'),
    path('students/view_by_course/<int:course_id>', views.StudentByCourseView, name='view_student_by_course'),

    path('courses', views.CourseView, name='courses'),
    path('courses/add', views.CourseCreateView, name='add_courses'),
    path('courses/update/<int:id>', views.CourseUpdateView, name='update_courses'),
    path('courses/delete/<int:id>', views.CourseDeleteView, name='delete_courses'),

    path('duration', views.DurationView, name='duration'),
    path('duration/add', views.DurationCreateView, name='add_duration'),
    path('duration/update/<int:id>', views.DurationUpdateView, name='update_duration'),
    path('duration/delete/<int:id>', views.DeleteDurationView, name='delete_duration'),

    path('fees', views.FeesView, name='fees'),
    path('fees/add', views.FeesCreateView, name='add_fees'),
    path('fees/update/<int:id>', views.FeesUpdateView, name='update_fees'),
    path('fees/delete/<int:id>', views.FeesDeleteView, name='delete_fees'),

    path('resources', views.ResourceView, name='resources'),
    path('resources/course/<int:courseId>', views.ResourceCourseView, name='course_resources'),
    path('resources/course/add/<int:courseId>', views.ResourceCourseCreateView, name='add_resources'),
    path('resources/course/update/<int:id>', views.ResourceCourseUpdateView, name='update_resources'),
    path('resources/course/delete/<int:id>', views.ResourceCourseDeleteView, name='delete_resource'),

    path('test', views.TestView, name='tests'),
    path('test/course/<int:courseId>', views.TestCourseView, name='course_tests'),
    path('test/course/add/<int:courseId>', views.TestQuestionCreateView, name='add_tests'),
    path('test/course/update/<int:id>', views.TestsCourseUpdateView, name='update_tests'),
    path('test/course/delete/<int:id>', views.TestCourseDeleteView, name='delete_tests'),

]

students/models.py
from django.db import models

# Create your models here.

teachers/models.py
from django.db import models

# Create your models here.

students/forms.py
from django import forms

from accounts.models import Courses


class CourseForm(forms.ModelForm):
    class Meta:
        model = Courses
        # fields="__all__"
        exclude = ('user_id',)
        widgets = {
            'course_title': forms.TextInput(attrs={'class': 'form-control', "placeholder": ""}),
            'course_description': forms.Textarea(attrs={'class': 'form-control', "placeholder": ""}),
            # 'course_thumbnail': forms.ImageField(attrs={'class': 'form-control'})
        }

teachers/forms.py
from django import forms

from accounts.models import Courses, Resources, Tests, Fees


class CourseForm(forms.ModelForm):
    class Meta:
        model = Courses
        # fields="__all__"
        exclude = ('user_id',)
        widgets = {
            'course_title': forms.TextInput(attrs={'class': 'form-control', "placeholder": ""}),
            'course_description': forms.Textarea(attrs={'class': 'form-control', "placeholder": ""}),
            # 'course_thumbnail': forms.ImageField(attrs={'class': 'form-control'})
        }


class CourseResourceForm(forms.ModelForm):
    class Meta:
        model = Resources
        # fields="__all__"
        exclude = ('course_id','resource_type')
        widgets = {
            'resource_title': forms.TextInput(attrs={'class': 'form-control', "placeholder": ""}),
            'resource_description': forms.Textarea(attrs={'class': 'form-control', "placeholder": ""}),
        }


class CourseQuestionForm(forms.ModelForm):
    class Meta:
        model = Tests
        # fields="__all__"
        exclude = ('course_id',)
        widgets = {
            'question': forms.TextInput(attrs={'class': 'form-control', "placeholder": ""}),
            'option1': forms.TextInput(attrs={'class': 'form-control', "placeholder": ""}),
            'option2': forms.TextInput(attrs={'class': 'form-control', "placeholder": ""}),
            'option3': forms.TextInput(attrs={'class': 'form-control', "placeholder": ""}),
            'option4': forms.TextInput(attrs={'class': 'form-control', "placeholder": ""}),
            'option5': forms.TextInput(attrs={'class': 'form-control', "placeholder": ""}),
        }


class FeesForm(forms.ModelForm):
    class Meta:
        model = Fees
        exclude = ('course_id',)
        widgets = {
            'price': forms.NumberInput(attrs={'class': 'form-control', "placeholder": ""}),
            'discount_percentage': forms.NumberInput(attrs={'class': 'form-control', "placeholder": ""}),
            'discount_amount': forms.TextInput(attrs={'class': 'form-control', "placeholder": ""}),
        }

teachers/templates/teachers/base.html
<!DOCTYPE html> {% load static %}
<html>

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no" />
    <title>{% block title %}Base{% endblock title %}</title>
    <link rel="stylesheet" href="{% static 'teachers/bootstrap/css/bootstrap.min.css' %}" />
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i" />
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=IM+Fell+Great+Primer+SC&amp;display=swap" />
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.12.0/css/all.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css" />
    <link rel="stylesheet" href="{% static 'teachers/fonts/fontawesome5-overrides.min.css' %}" />
      <style>
      .sidebar-dark {
         background-color: #19222D;
        }
       .navbar-light,.bg-primary {
            background-color: #031F42;
        }
        .card{
        color:#f3f3ff;
        background-color: #031F42;
         border-radius:20px;
        }

        .card>img {
             transition: transform .5s ease-in-out;
          transform-origin: 0 0;
         }
         .max-lines {
         -webkit-line-clamp: 2;
          text-overflow: ellipsis;
          overflow: hidden;
        }
         li.active{
                background-color:#020E1B;
                }
  </style>
</head>

<body id="page-top">
    <div id="wrapper">
        <nav class="navbar navbar-dark align-items-start sidebar sidebar-dark accordion  p-0 position-sticky fixed-top">
            <div class="container-fluid d-flex flex-column p-0 ">
                <a class="navbar-brand d-flex justify-content-center align-items-center sidebar-brand m-0" href="{% url 'teachers:dashboard' %}">
                    <div class="sidebar-brand-icon"><i class="fa fa-dashcube"></i></div>
                    <div class="sidebar-brand-text mx-3"><span>TEACHER</span></div>

                </a>
                <hr class="sidebar-divider my-0" />
                <ul class="navbar-nav text-light" id="accordionSidebar">

                    <li class="nav-item">
                        <a class="nav-link active" href="{% url 'teachers:dashboard' %}"><i
                                                class="fas fa-inbox fa-sm fa-fw mr-2 text-gray-400"></i> <span>Dashboard</span></a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href=" {% url 'teachers:students' %}"><i
                                                class="fa fa-graduation-cap fa-sm fa-fw mr-2 text-gray-400"></i> <span>Students</span></a>
                    </li>
                     <li class="nav-item">
                        <a class="nav-link" href="{% url 'teachers:courses' %}"><i
                                                class="fa fa-book fa-sm fa-fw mr-2 text-gray-400"></i> <span>Courses</span></a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'teachers:resources' %}"><i
                                                class="fa fa-folder fa-sm fa-fw mr-2 text-gray-400"></i> <span>Study Resources</span></a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'teachers:duration' %}"><i
                                                class="fa fa-calendar fa-sm fa-fw mr-2 text-gray-400" ></i> <span>Duration</span></a>
                    </li>
                     <li class="nav-item">
                        <a class="nav-link" href="{% url 'teachers:fees' %}"><i
                                                class="fa fa-money fa-sm fa-fw mr-2 text-gray-400"></i> <span>Fees</span></a>
                    </li>
                     <li class="nav-item">
                        <a class="nav-link" href="{% url 'teachers:tests' %}"><i
                                                class="fa fa-graduation-cap fa-sm fa-fw mr-2 text-gray-400"></i> <span>Test</span></a>
                    </li>
<!--                     <li class="nav-item">-->
<!--                        <a class="nav-link" href=""><i-->
<!--                                                class="fa fa-file fa-sm fa-fw mr-2 text-gray-400"></i> <span>Results</span></a>-->
<!--                    </li>-->
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'accounts:logout' %}">
                           <i class="fas fa-sign-out-alt fa-sm fa-fw mr-2 text-gray-400"></i>
                            <span>Log out</span></a>
                    </li>

                </ul>
                <div class="text-center my-auto d-none d-md-inline">
                    <button class="btn rounded-circle border-0 btn-success" id="sidebarToggle" type="button"></button>
                </div>
            </div>
        </nav>
        <div class="d-flex flex-column" id="content-wrapper">
            <div id="content sticky-top">
                <nav class="navbar navbar-light navbar-expand shadow mb-4 topbar  sticky-top">
                    <div class="container-fluid">

                        <button class="btn btn-link d-md-none rounded-circle mr-3" id="sidebarToggleTop" type="button">
                            <i class="fas fa-bars"></i>
                        </button>
                        <form class="form-inline d-none d-sm-inline-block mr-auto ml-md-3 my-2 my-md-0 mw-100 navbar-search" method="POST"  action="{% url 'teachers:search' %}">
                            <div class="input-group">
                                {% csrf_token %}
                                <input class="bg-light form-control border-0 small" type="text" name="search" placeholder="Enter a course code or course name ..." />
                                <div class="input-group-append">
                                    <button class="btn btn-primary py-0" type="submit">
                                        <i class="fas fa-search"></i>
                                    </button>
                                </div>
                            </div>
                        </form>
                        <ul class="navbar-nav flex-nowrap ml-auto">
                            <li class="nav-item dropdown d-sm-none no-arrow">
                                <a class="dropdown-toggle nav-link" aria-expanded="false" data-toggle="dropdown" href="#"><i class="fas fa-search"></i></a>
                                <div class="dropdown-menu dropdown-menu-right p-3 animated--grow-in" aria-labelledby="searchDropdown">
                                    <form class="form-inline mr-auto navbar-search w-100" method="POST"  action="{% url 'admins:search' %}">
                                            {% csrf_token %}
                                            <div class="input-group">
                                            <input class="bg-light form-control border-0 small" type="text" name="search" placeholder="Enter a course code or course name ..." />
                                            <div class="input-group-append">
                                                <button class="btn btn-primary py-0" type="submit">
                                                    <i class="fas fa-search"></i>
                                                </button>
                                            </div>
                                        </div>
                                    </form>
                                </div>
                            </li>
                            <div class="d-none d-sm-block topbar-divider"></div>
                            <li class="nav-item dropdown no-arrow">
                                <div class="nav-item dropdown no-arrow">
                                    <a class="dropdown-toggle nav-link" aria-expanded="false" data-toggle="dropdown" href="#">
                                        <span class="d-none d-lg-inline mr-2 text-gray-600 small">
                                            {{user.name|upper}}
                                        </span>
                                        {% if user.profile_image %}
                                            <img class="rounded-circle border img-profile" src="{{user.profile_image.url}}"/>
                                         {% else %}
                                            <img class="rounded-circle border img-profile" src="{% static 'teachers/img/avatars/img.png' %}" />
                                        {% endif %}
                                    </a>
                                    <div class="dropdown-menu shadow dropdown-menu-right animated--grow-in">
                                        <a class="dropdown-item" href="{% url 'teachers:edit_account' %}"><i
                                                class="fas fa-user fa-sm fa-fw mr-2 text-gray-400"></i>&nbsp;Profile</a>
                                        <div class="dropdown-divider"></div>
                                        <a class="dropdown-item" href="{% url 'teachers:change_password' %}"><i
                                                class="fas fa-unlock-alt fa-sm fa-fw mr-2 text-gray-400"></i>Change Password</a>
                                        <div class="dropdown-divider"></div>
                                        <a class="dropdown-item" href="{% url 'accounts:logout' %}"><i
                                                class="fas fa-sign-out-alt fa-sm fa-fw mr-2 text-gray-400"></i>&nbsp;Logout</a>
                                    </div>
                                </div>
                            </li>
                        </ul>
                    </div>
                </nav>
                <div class="mb-5">
                    <!-- Body Block : START -->
                    {% block content %}

                    <!-- Body Block : END -->
                    {% endblock content %}
                </div>

            </div>
<!--            <footer class="bg-white sticky-footer">-->
<!--                <div class="container my-auto">-->
<!--                        <div class="text-right my-auto copyright">-->
<!--                        <span>Copyright © OLS 2022</span>-->
<!--                    </div>-->
<!--                </div>-->
<!--            </footer>-->
        </div>
<!--        <a class="border rounded d-inline scroll-to-top" href="#page-top"><i class="fas fa-angle-up"></i></a>-->
    </div>
     {% block script %}

    {% endblock script %}
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.6.1/js/bootstrap.bundle.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-easing/1.4.1/jquery.easing.js"></script>
    <script src="{% static 'teachers/js/theme.js' %}"></script>
    <script>
        $(document).ready(function() {
          $('li.active').removeClass('active').removeAttr('aria-current');
          $('a[href="' + location.pathname + '"]').closest('li').addClass('active').attr('aria-current', 'page');
        });
    </script>
</body>

</html>

teachers/templates/teachers/courses.html
{% extends 'teachers/base.html' %} {% block title %}Courses{% endblock title %} {% block content %}
{% load static %}

<div class="container-fluid">
    <div class="card shadow  card-body p-2 ">
      <h5 class="pt-2 "><i class="fa fa-book fa-sm fa-fw mr-2 text-gray-400"></i>Courses</h5>
    </div>

     <a class="btn btn-primary btn-icon-split mt-4" role="button" href="{% url 'teachers:add_courses' %}">
        <span class="text-white-50 icon">
            <i class="fas fa-plus fa-sm text-gray-400"></i>
        </span>
        <span class="text-white text small">Add Courses</span>
    </a>
    {% if messages %}
      {% for message in messages %}
        <div class="alert alert-dismissible {{ message.tags }} mt-3">
          <button type="button" class="close" data-dismiss="alert">
          ×
          </button>
          <strong>{{message}}</strong>
        </div>
     {% endfor %}
    {% endif %}

    <div class="table-responsive mt-4">
      <table class="table table-sm table-bordered ">
<!--        <caption>List of roles</caption>-->
          <thead>
            <tr class="bg-secondary text-white small">
              <th scope="col">SN</th>
              <th scope="col">Course code</th>
              <th scope="col">Course title</th>
                <th scope="col">Course Image</th>
              <th scope="col text-align-right">Actions</th>
            </tr>
          </thead>
          <tbody>
          {% if courses %}
          {% for course in courses %}
            <tr class="small">
              <td scope="row">{{ forloop.counter }}</td>
              <td scope="row">{{ course.code }}</td>
              <td class="max-lines">{{course.course_title}}</td>
<!--              <td class="max-lines">{{course.course_description}}</td>-->
              <td scope="row">
                  {% if course.course_thumbnail %}
                      <img src="{{ course.course_thumbnail.url }}" class="img-responsive" height="30" width="100" alt="No image" />
                  {% endif %}
              </td>
              <td>
                <div class="pull-right dropdown no-arrow justify-content-right">

                    <button
                      class="btn btn-link btn-sm dropdown-toggle"
                      aria-expanded="false"
                      data-toggle="dropdown"
                      type="button"
                    >
                      <i class="fas fa-ellipsis-v "></i>
                    </button>
                    <div class="dropdown-menu shadow dropdown-menu-right animated--fade-in">
                      <a class="dropdown-item btn-success" href="{% url 'teachers:update_courses' id=course.id %}">
                          <i class="fa fa-edit fa-sm fa-fw mr-2 text-gray-400"></i>
                          &nbsp;Edit Course
                      </a>
                      <a class="dropdown-item" href="{% url 'teachers:delete_courses' id=course.id %}">
                          <i class="fa fa-trash-o fa-sm fa-fw mr-2 text-gray-400"></i>
                          &nbsp;Delete Course
                      </a>
                    </div>
                  </div>
              </td>
            </tr>
            {% endfor %}
            {% else %}
              <tr>
                  <td colspan="4" class="small">No courses has been added</td>
              </tr>
              {% endif %}
          </tbody>
      </table>
    </div>

</div>

{% endblock content %}

teachers/templates/teachers/dashboard.html
{% extends 'teachers/base.html' %} {% block title %}Dashboard{% endblock title %} {% block content %}

<div class="container-fluid">
        {% if messages %}
          {% for message in messages %}
            <div class="alert alert-dismissible {{ message.tags }} mt-3">
              <button type="button" class="close" data-dismiss="alert">
              ×
              </button>
              <strong>{{message}}</strong>
            </div>
         {% endfor %}
    {% endif %}
    <div class="card shadow  card-body p-2 ">
      <h5 class="pt-2 "><i class="fas fa-inbox fa-sm fa-fw mr-2 text-gray-400"></i>Dashboard</h5>
    </div>

    <div class="row justify-content-left mt-4">
        <div class="col-lg-3 ">
            <div class="card shadow mb-4">
                <div class="card-body p-3 btn-warning">
                    <h6>Students available</h6>
                    <hr>
                    <h6>{{students_count}}</h6>
                </div>
            </div>
        </div>
        <div class="col-lg-3">
            <div class="card shadow mb-4">
                <div class="card-body p-3 btn-success">
                    <h6>Enrolled Students</h6>
                    <hr>
                    <h6>{{enroll_count}}</h6>
                </div>
            </div>
        </div>
        <div class="col-lg-3">
            <div class="card mb-4">
                <div class="card-body p-3 btn-primary">
                    <h6>Courses Created</h6>
                    <hr>
                    <h6>{{courses_count}}</h6>
                </div>
            </div>
        </div>
        <div class="col-lg-3">
            <div class="card shadow mb-4">
                <div class="card-body p-3 btn-info">
                    <h6>Fees Paid</h6>
                    <hr>
                    <h6>{{fees_paid_count}}</h6>
                </div>
            </div>
        </div>
    </div>

    <h4>Courses</h4>
    <!-- Start: break 4.0 --><br>
    <!-- End: break 4.0 -->
    <!-- Start: Dropdown Card -->
    {% if courses_of_admins %}
     {% for course in courses_of_admins %}
        <div class="card shadow mb-4 animated--fade-in">
            <div class="card-header d-flex justify-content-between align-items-center">
                <h6 class="text-primary m-0 font-weight-bold">{{course.course_title}}</h6>
                <div class="dropdown no-arrow"><button class="btn btn-link btn-sm dropdown-toggle" aria-expanded="false" data-toggle="dropdown" type="button"><i class="fas fa-ellipsis-v text-gray-400"></i></button>
                    <div class="dropdown-menu shadow dropdown-menu-right animated--fade-in">
                        <a class="dropdown-item text-danger" href="{% url 'teachers:delete_courses' id=course.id %}">Delete Course</a>
                        <a class="dropdown-item text-success" href="{% url 'teachers:update_courses' id=course.id %}">Edit Course</a>
                    </div>
                </div>
            </div>
            <div class="card-body">
                <p class="m-0 text-gray-500">Course code : {{course.code}}<br></p>
                <br>
                <div class="row">
                    <div class="col">
                        <a class="btn btn-primary btn-icon-split" role="button" href="{% url 'teachers:course_resources' courseId=course.id %}"><span
                                class="text-white-50 icon"><i class="far fa-folder"></i></span><span
                                class="text-white text">Manage Resources</span>
                        </a>
                        <a class="btn btn-primary btn-icon-split" role="button" href="{% url 'teachers:course_tests' courseId=course.id %}"><span
                                class="text-white-50 icon"><i class="far fa-folder"></i></span><span
                                class="text-white text">Manage Tests</span>
                        </a>
                    </div>
                    <div class="col text-right">
                        <a class="btn btn-warning btn-icon-split" role="button" href="{% url 'teachers:view_student_by_course' course_id=course.id %}"><span
                                class="text-white-50 icon"><i class="far fa-user"></i></span><span
                                class="text-white text">Students</span></a>
                    </div>
                </div>
            </div>
        </div>
    {% endfor %}
    {% else %}
        <div class="d-flex align-items-center justify-content-center flex-column">
           <label><b class="text-primary pt-4">No Courses are added.</b></label><br/>
           <a href="{% url 'teachers:courses' %}" class="form-button btn btn-primary">Add Course</a>
        </div>
    {% endif %}
</div>

{% endblock content %}