OnlineLearning/urls.py
from .views import HomeView, DashboardView
from django.conf.urls.static import static
from django.urls import include, path
from django.conf import settings
from . import views
from django.conf.urls import (handler400, handler403, handler404, handler500)

# handler404 = "OnlineLearning.views.page_not_found"

urlpatterns = [
    # path('', views.insert)
    path("", view=HomeView.as_view(), name='home'),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('dashboard/', DashboardView, name='dashboard'),
    path('teachers/', include('teachers.urls', namespace='teachers')),
    path('admins/', include('admins.urls', namespace='admins')),
    path('students/', include('students.urls', namespace='students')),

    # path('signup', views.signup, name="signup"),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    # if settings.DEBUG:

admins/urls.py
from django.urls import include, path
from .views import DashboardView,RolesView,RolesCreateView,RolesDeleteView,RolesEditView,RolesUpdateView
from . import views
app_name = 'admins'

urlpatterns = [
    path('', DashboardView, name='dashboard'),

    path('profile/edit', views.AccountUpdateView, name='edit_account'),

    path('user/update/<int:user_id>', views.UserUpdateView, name='edit_users'),
    path('user/delete/<int:user_id>/<int:check_user>', views.UserDeleteView, name='delete_users'),

    path('change_pass', views.ChangePasswordView, name='change_password'),

    path('search', views.SearchResultView, name='search'),

    path('roles/', RolesView, name='roles'),
    path('roles/add/', RolesCreateView, name='add_roles'),
    path('roles/delete/<int:id>', RolesDeleteView, name='delete_roles'),
    path('roles/edit/<int:id>', RolesEditView, name='edit_roles'),
    path('roles/update/<int:id>', RolesUpdateView, name='update_roles'),

    path('courses/', views.CourseView, name='courses'),
    path('courses/add', views.CourseCreateView, name='add_courses'),
    path('courses/update/<int:id>', views.CourseUpdateView, name='update_courses'),
    path('courses/delete/<int:id>', views.CourseDeleteView, name='delete_courses'),
    path('courses/all', views.CourseViewAll, name='view_all_courses'),

    path('students/', views.StudentView, name='student'),
    path('students/view/<int:id>', views.StudentDetailView, name='view_student'),
    path('students/view/payment/<int:course_id>/<int:id>', views.StudentPaymentDetailView, name='view_student_payment'),
    path('students/view_by_course/<int:course_id>', views.StudentByCourseView, name='view_student_by_course'),

    path('teachers/', views.TeacherView, name='teacher'),
    path('teacher/view/<int:id>', views.TeacherDetailView, name='view_teacher'),

    path('duration', views.DurationView, name='duration'),
    path('duration/add', views.DurationCreateView, name='add_duration'),
    path('duration/update/<int:id>', views.DurationUpdateView, name='update_duration'),
    path('duration/delete/<int:id>', views.DeleteDurationView, name='delete_duration'),
    path('duration/all', views.DurationViewAll, name='view_all_duration'),

    path('fees', views.FeesView, name='fees'),
    path('fees/add', views.FeesCreateView, name='add_fees'),
    path('fees/update/<int:id>', views.FeesUpdateView, name='update_fees'),
    path('fees/delete/<int:id>', views.FeesDeleteView, name='delete_fees'),
    path('fees/all', views.FeesViewAll, name='view_all_fees'),

    path('resources', views.ResourceView, name='resources'),
    path('resources/course/<int:courseId>', views.ResourceCourseView, name='course_resources'),
    path('resources/course/add/<int:courseId>', views.ResourceCourseCreateView, name='add_resources'),
    path('resources/course/update/<int:id>', views.ResourceCourseUpdateView, name='update_resources'),
    path('resources/course/delete/<int:id>', views.ResourceCourseDeleteView, name='delete_resource'),
    path('resources/all', views.ResourceViewAll, name='view_all_resources'),

    path('test', views.TestView, name='tests'),
    path('test/course/<int:courseId>', views.TestCourseView, name='course_tests'),
    path('test/course/add/<int:courseId>', views.TestQuestionCreateView, name='add_tests'),
    path('test/course/update/<int:id>', views.TestsCourseUpdateView, name='update_tests'),
    path('test/course/delete/<int:id>', views.TestCourseDeleteView, name='delete_tests'),
    path('tes/all', views.TestViewAll, name='view_all_tests'),

]

students/urls.py
from django.urls import include, path
from .views import DashboardView
from . import views


app_name = 'students'

urlpatterns = [
    path('', DashboardView, name='dashboard'),

    path('profile/edit', views.AccountUpdateView, name='edit_account'),

    path('courses', views.CoursesView, name='courses'),

    path('search', views.SearchResultView, name='search'),

    path('change_pass', views.ChangePasswordView, name='change_password'),

    path('course_detail/<int:id>', views.CourseDetailView, name='course_detail'),
    path('course_enroll/<int:id>', views.CourseEnrollView, name='course_enroll'),
    path('course_unroll/<int:id>', views.CourseUnrollView, name='course_unroll'),

    path('payments/<int:id>', views.PaymentView, name='payments'),

    path('tests', views.TestView, name='tests'),
    path('tests/<int:courseId>', views.CourseTestView, name='course_test'),

]

teachers/urls.py
from django.conf.urls.static import static
from django.urls import include, path
from django.conf import settings
from .views import DashboardView
from . import views

app_name = 'teachers'

urlpatterns = [
    path('', DashboardView, name='dashboard'),

    path('profile/edit', views.AccountUpdateView, name='edit_account'),
    path('change_pass', views.ChangePasswordView, name='change_password'),

    path('search', views.SearchResultView, name='search'),

    path('students', views.StudentView, name='students'),
    path('students/view/<int:id>', views.StudentDetailView, name='view_student'),
    path('students/view/payment/<int:course_id>/<int:id>', views.StudentPaymentDetailView, name='view_student_payment'),
    path('students/view_by_course/<int:course_id>', views.StudentByCourseView, name='view_student_by_course'),

    path('courses', views.CourseView, name='courses'),
    path('courses/add', views.CourseCreateView, name='add_courses'),
    path('courses/update/<int:id>', views.CourseUpdateView, name='update_courses'),
    path('courses/delete/<int:id>', views.CourseDeleteView, name='delete_courses'),

    path('duration', views.DurationView, name='duration'),
    path('duration/add', views.DurationCreateView, name='add_duration'),
    path('duration/update/<int:id>', views.DurationUpdateView, name='update_duration'),
    path('duration/delete/<int:id>', views.DeleteDurationView, name='delete_duration'),

    path('fees', views.FeesView, name='fees'),
    path('fees/add', views.FeesCreateView, name='add_fees'),
    path('fees/update/<int:id>', views.FeesUpdateView, name='update_fees'),
    path('fees/delete/<int:id>', views.FeesDeleteView, name='delete_fees'),

    path('resources', views.ResourceView, name='resources'),
    path('resources/course/<int:courseId>', views.ResourceCourseView, name='course_resources'),
    path('resources/course/add/<int:courseId>', views.ResourceCourseCreateView, name='add_resources'),
    path('resources/course/update/<int:id>', views.ResourceCourseUpdateView, name='update_resources'),
    path('resources/course/delete/<int:id>', views.ResourceCourseDeleteView, name='delete_resource'),

    path('test', views.TestView, name='tests'),
    path('test/course/<int:courseId>', views.TestCourseView, name='course_tests'),
    path('test/course/add/<int:courseId>', views.TestQuestionCreateView, name='add_tests'),
    path('test/course/update/<int:id>', views.TestsCourseUpdateView, name='update_tests'),
    path('test/course/delete/<int:id>', views.TestCourseDeleteView, name='delete_tests'),

]

students/views.py
import os

from django.shortcuts import render, redirect
from accounts.models import Roles, Users, Courses, Duration, Resources, Enrolls, Tests, Fees, FeesPayment
from accounts.forms import UserEditForm, ChangePasswordForm
from django.contrib import messages
from OnlineLearning import views
from accounts.decorators import unauthenticated_user
from datetime import date
from django.db.models import Q
from django.contrib.auth.hashers import make_password, check_password
from PIL import Image
from django.shortcuts import get_object_or_404
today = date.today()

def check_img(filename):
    try:
        Image.open(filename)
        return True
    except IOError:
        return False


@unauthenticated_user
def DashboardView(request):
    return render(request, 'students/dashboard.html', views.ContextForStudents(request))


@unauthenticated_user
def AccountUpdateView(request):
    users = Users.objects.get(id=request.session['user_id'])
    form = UserEditForm(instance=users)
    if request.method == "POST":
        form = UserEditForm(request.POST, request.FILES, instance=users)
        if form.is_valid:
            try:
                form.save()
                messages.success(request, 'Your profile has been edited successfully.')
                return redirect('students:dashboard')
            except:
                pass

    return render(request, "students/edit_account.html", {'form': form, 'user': users})


@unauthenticated_user
def CourseDetailView(request, id):
    # try:
        courses = Courses.objects.get(id=id)
        duration = get_object_or_404(Duration, course_id=id)
        enrolls_total = Enrolls.objects.filter(course_id=id).count()
        fee = Fees.objects.get(course_id=courses)
        users = Users.objects.get(id=request.session['user_id'])
        is_paid = False
        check_paid = FeesPayment.objects.filter(course_id=courses, paid_from=users)
        if check_paid.exists():
            is_paid = True
        return render(request, "students/course_detail.html", {'courses': courses, 'duration': duration,
                                                                   'enrolls_total': enrolls_total, 'fees': fee,
                                                                   'user': users, 'is_paid': is_paid, })
    # except:
    #     pass



@unauthenticated_user
def CourseEnrollView(request, id):
    courses = Courses.objects.get(id=id)
    duration = Duration.objects.get(course_id=id)
    resource = Resources.objects.filter(course_id=id)
    fee = Fees.objects.get(course_id=id)
    user = Users.objects.get(id=request.session['user_id'])
    check_paid = FeesPayment.objects.filter(course_id=courses, paid_from=user)
    payment = []
    paid_fee = 0
    if check_paid.exists():
        for v in check_paid:
            payment.append(v)
    if len(payment) > 0:
        paid_fee = payment[0].paid_amount

    enrolls = Enrolls(
        course_id=courses,
        user_id=user,
        teacher_id=courses.user_id.id
    )
    payment_image = ''
    payment_mode = 'Card'

    if 'voucher_image' in request.FILES :
        payment_image = request.FILES['voucher_image']
        payment_mode = 'Bank account'
        if not check_img(payment_image):
            messages.error(request, 'The image is not supported.')
            return redirect('students:payments', id=id)

    price = fee.price

    feesPayment = FeesPayment(
        course_id=courses,
        paid_amount=price,
        payment_image=payment_image,
        payment_method=payment_mode,
        status=1,
        paid_from=user,
        paid_to=courses.user_id.id,
    )

    if request.method == "POST":

            new = Enrolls.objects.filter(course_id=courses, user_id=user)
            payments = FeesPayment.objects.filter(course_id=courses, paid_from=user)
            if new.exists():
                messages.error(request, 'Selected course already enrolled.')
                return redirect('students:course_detail', id=id)
            elif payments.exists() or fee.is_free:
                enrolls.save()
                messages.success(request, 'You have successfully enrolled this subject.')
            else:
                feesPayment.save()
                enrolls.save()
                messages.success(request, 'You have successfully enrolled this subject.')

    enrolls_total = Enrolls.objects.filter(course_id=id).count()
    return render(request, "students/course_enroll.html", {'courses': courses, 'duration': duration,
                                                           'resources': resource, 'enrolls_total': enrolls_total,
                                                           'fees': fee, 'user': user, "payment": paid_fee})


@unauthenticated_user
def CourseUnrollView(request, id):
    courses = Courses.objects.get(id=id)
    user = Users.objects.get(id=request.session['user_id'])
    enroll = Enrolls.objects.get(course_id=courses, user_id=user)
    enroll.delete()
    messages.success(request, 'Selected course remove from enroll.')
    return redirect("students:course_detail", id=id)


@unauthenticated_user
def CoursesView(request):
    return render(request, "students/courses.html", views.ContextForStudents(request))


@unauthenticated_user
def TestView(request):
    return render(request, "students/test.html", views.ContextForStudents(request))


@unauthenticated_user
def PaymentView(request, id):
    courses = Courses.objects.get(id=id)
    duration = Duration.objects.get(course_id=id)
    resource = Resources.objects.filter(course_id=id)
    fee = Fees.objects.get(course_id=id)
    enrolls_total = Enrolls.objects.filter(course_id=id).count()
    user = Users.objects.get(id=request.session['user_id'])
    context = {'courses': courses,
               'duration': duration,
               'resources': resource,
               'enrolls_total': enrolls_total,
               'fees': fee,
               'user': user}
    return render(request, "students/payment.html", context)


@unauthenticated_user
def CourseTestView(request, courseId):
    courses = Courses.objects.get(id=courseId)
    test = Tests.objects.filter(course_id=courseId)
    duration = Duration.objects.get(course_id=courseId)
    user = Users.objects.get(id=request.session['user_id'])
    check_paid = FeesPayment.objects.filter(course_id=courses, paid_from=user)
    payment = []
    paid_fee = 0
    if check_paid.exists():
        for v in check_paid:
            payment.append(v)
    if len(payment) > 0:
        paid_fee = payment[0].paid_amount

    if request.method == 'POST':
        questions = Tests.objects.filter(course_id=courseId)
        score = 0
        wrong = 0
        correct = 0
        total = 0
        for q in questions:
            total += 1
            if q.correct == request.POST.get(q.question):
                score += 10
                correct += 1
            else:
                wrong += 1
        percent = score / (total * 10) * 100
        context = {
            'score': score,
            'time': request.POST.get('timer'),
            'correct': correct,
            'wrong': wrong,
            'percent': percent,
            'total': total,
            'courses': courses,
            'tests': test,
            'user': user,
            'issue_date': today.strftime("%B %d, %Y"),
        }
        return render(request, 'students/certificate.html', context)
    else:
        questions = test
        enrolls_total = Enrolls.objects.filter(course_id=courseId).count()
        context = {'duration': duration, 'enrolls_total': enrolls_total, 'questions': questions, 'courses': courses,
                   'tests': test, 'user': user, "payment": paid_fee}

    return render(request, "students/course_test.html", context)


def SearchResultView(request):
    user = Users.objects.get(id=request.session['user_id'])

    if request.method == 'POST':
        search_text = request.POST.get('search')
        # course = Courses.objects.get(Q( title__icontains=search_text) & Q(content__icontains=search_text))

        courses = Courses.objects.filter(Q(course_title__icontains=search_text)
                                    | Q(code__icontains=search_text))
        fees = Fees.objects.all()

        fees_data = []
        for elem in courses:
            for v in fees:
                if v.course_id.id == elem.id:
                    fees_data.append(v)

    return render(request, "students/search_result.html", {"fees": fees_data,
                                                           "search_text": search_text,
                                                           "course_count": len(fees_data), 'user': user
                                                           })


def ChangePasswordView(request):
    user = Users.objects.get(id=request.session['user_id'])
    form = ChangePasswordForm()
    if request.method == 'POST':
        old_password = request.POST.get('old_password')
        new_password = request.POST.get('new_password')
        retype_password = request.POST.get('retype_password')
        check_pwd = check_password(old_password, user.password)

        if old_password == '' or new_password == '' or retype_password =='':
            messages.error(request, 'All fields are mandatory.')
        elif check_pwd == False:
            messages.error(request, 'Your entered password with old password doesn\'t match.')
        elif new_password != retype_password:
            messages.error(request, 'Your retype password is not match with new password.')
        else:
            user.password = make_password(new_password)
            user.save()
            messages.success(request, 'Your password is changed successfully.')
            redirect('students:dashboard')
    return render(request, "students/change_password.html", {"form": form,  'user': user})

admins/templates/admins/course_resources.html
{% extends 'admins/base.html' %} {% block title %}Resources{% endblock title %} {% block content %}
{% load static %}

<div class="container-fluid">
    <div class="card shadow  card-body p-2 ">
      <h5 class="pt-2 "><i class="fa fa-folder fa-sm fa-fw mr-2 text-gray-400"></i>Study Resources</h5>
    </div>


    {% if messages %}
      {% for message in messages %}
        <div class="alert alert-dismissible {{ message.tags }} mt-3">
          <button type="button" class="close" data-dismiss="alert">
          ×
          </button>
          <strong>{{message}}</strong>
        </div>
     {% endfor %}
    {% endif %}

    {% if courses %}
    {% for course in courses %}
    <div class="card shadow mb-4 mt-3">
        <div class="card-header d-flex justify-content-between align-items-center">
            <h6 class="text-primary m-0 font-weight-bold">{{course.course_title}}</h6>
            <div class="dropdown no-arrow"><button class="btn btn-link btn-sm dropdown-toggle" aria-expanded="false" data-toggle="dropdown" type="button"><i class="fas fa-ellipsis-v text-gray-400"></i></button>
                <div class="dropdown-menu shadow dropdown-menu-right animated--fade-in"><a class="dropdown-item text-danger" href="">Delete Course</a></div>
            </div>
        </div>
        <div class="card-body">
            <p class="m-0 text-gray-500">Course code : {{course.code}}<br></p>
            <br>
            <div class="row">
                <div class="col">
                    <!-- Start: Split Button Primary -->
                    <a class="btn btn-primary btn-icon-split" role="button" href="{% url 'admins:add_resources' courseId=course.id %}"><span
                            class="text-white-50 icon"><i class="far fa-folder"></i></span><span
                            class="text-white text">Add Resources</span>
                    </a>
                   <a class="btn btn-info btn-icon-split" role="button" href="{% url 'admins:dashboard' %}"><span
                            class="text-white-50 icon"><i class="far fa-times-circle"></i></span><span
                            class="text-white text">Cancel</span>
                    </a>
                </div>
                <div class="col text-right">
                    <a class="btn btn-warning btn-icon-split" role="button" href="{% url 'admins:view_student_by_course' course_id=course.id %}"><span
                            class="text-white-50 icon"><i class="far fa-user"></i></span><span
                            class="text-white text">Students</span></a>
                </div>
            </div>
        </div>
    </div>
    {% endfor %}
    {% else %}
      <div>
          <h6  class="text-primary m-0 font-weight-bold small">No courses is found</h6>
      </div>
      {% endif %}

        <div class="card shadow  card-body p-2 mb-3">
          <h5 class="pt-2 "><i class="fa fa-file fa-sm fa-fw mr-2 text-gray-400"></i>Added Resources</h5>
        </div>
        <div>
        {% if resource %}
        {% for resource in resource %}
        <div class="shadow card"><a class="btn btn-link text-left card-header font-weight-bold" data-toggle="collapse" aria-expanded="true" aria-controls="collapse-4-{{resource.id|slugify}}" href="#collapse-4-{{resource.pk|slugify}}" role="button">{{forloop.counter}}. {{resource.resource_title}}</a>
            <div class="collapse" id="collapse-4-{{resource.pk|slugify}}">
                <div class="card-body">
                    <h1 style="font-size: 14px;font-weight: bold;">{{resource.date_created|date:"M d, Y"}}</h1>
                    <hr>
                    <p class="m-0">{{resource.resource_description|linebreaksbr}}</p>
                   <br>

                    <div class="row">
                        {% if resource.resource %}
                        <div class="col">
                           <a class="btn btn-primary btn-icon-split" role="button" href="{{resource.resource.url}}" target="_blank">
                               <span class="text-white-50 icon">
                                   <i class="fas fa-eye"></i>
                               </span>
                               <span class="text-white text">
                                   View Resource
                               </span>
                           </a>
                        </div>
                        <div class="col">
                           <a class="btn btn-success btn-icon-split" role="button" href="" download><span class="text-white-50 icon"><i class="fas fa-arrow-circle-down"></i></span><span class="text-white text">Download Resource</span></a>
                        </div>
                        <div class="col">
                         <a class="btn btn-success btn-icon-split" role="button" href="{% url 'admins:update_resources' id=resource.id %}">
                             <span class="text-white-50 icon">
                                 <i class="fas fa-edit">
                             </i>
                             </span>
                             <span class="text-white text">Edit Resource</span></a>

                        </div>
                        {% endif %}
                        <div class="col text-right">
                            <a class="btn btn-danger btn-icon-split" role="button" href="{% url 'admins:delete_resource' id=resource.id %}">
                                <span class="text-white-50 icon">
                                    <i class="fa fa-trash-o fa-sm fa-fw mr-2 text-gray-400"></i>
                                    </span><span class="text-white text">Delete</span></a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        {% endfor %}
        {% else %}
        <div>
          <h6  class="text-primary m-0 font-weight-bold small">No resources are added.</h6>
        </div>
        {% endif %}

       <br>

    </div>

</div>

{% endblock content %}

admins/templates/admins/courses.html
{% extends 'admins/base.html' %} {% block title %}Courses{% endblock title %} {% block content %}
{% load static %}

<div class="container-fluid">
    <div class="card shadow  card-body p-2 ">
      <h5 class="pt-2 "><i class="fa fa-book fa-sm fa-fw mr-2 text-gray-400"></i>Courses</h5>
    </div>

     <a class="btn btn-primary btn-icon-split mt-4" role="button" href="{% url 'admins:add_courses' %}">
        <span class="text-white-50 icon">
            <i class="fas fa-plus fa-sm text-gray-400"></i>
        </span>
        <span class="text-white text small">Add Courses</span>
    </a>
    <a class="btn btn-secondary btn-icon-split mt-4" role="button" href="{% url 'admins:view_all_courses' %}">
        <span class="text-white-50 icon">
            <i class="fas fa-eye fa-sm text-gray-400"></i>
        </span>
        <span class="text-white text small">View All</span>
    </a>
    {% if messages %}
      {% for message in messages %}
        <div class="alert alert-dismissible {{ message.tags }} mt-3">
          <button type="button" class="close" data-dismiss="alert">
          ×
          </button>
          <strong>{{message}}</strong>
        </div>
     {% endfor %}
    {% endif %}

    <div class="table-responsive mt-4">
      <table class="table table-sm table-bordered ">
<!--        <caption>List of roles</caption>-->
          <thead>
            <tr class="bg-secondary text-white small">
              <th scope="col">SN</th>
              <th scope="col">Course code</th>
              <th scope="col">Course title</th>
                <th scope="col">Course Image</th>
              <th scope="col text-align-right">Actions</th>
            </tr>
          </thead>
          <tbody>
          {% if courses %}
          {% for course in courses %}
            <tr class="small">
              <td scope="row">{{ forloop.counter }}</td>
              <td scope="row">{{ course.code }}</td>
              <td class="max-lines">{{course.course_title}}</td>
<!--              <td class="max-lines">{{course.course_description}}</td>-->
              <td scope="row">
                  {% if course.course_thumbnail %}
                      <img src="{{ course.course_thumbnail.url }}" class="img-responsive" height="30" width="100" alt="No image" />
                  {% endif %}
              </td>
              <td>
                <div class="pull-right dropdown no-arrow justify-content-right">

                    <button
                      class="btn btn-link btn-sm dropdown-toggle"
                      aria-expanded="false"
                      data-toggle="dropdown"
                      type="button"
                    >
                      <i class="fas fa-ellipsis-v "></i>
                    </button>
                    <div class="dropdown-menu shadow dropdown-menu-right animated--fade-in">
                      <a class="dropdown-item btn-success" href="{% url 'admins:update_courses' id=course.id %}">
                          <i class="fa fa-edit fa-sm fa-fw mr-2 text-gray-400"></i>
                          &nbsp;Edit Course
                      </a>
                      <a class="dropdown-item" href="{% url 'admins:delete_courses' id=course.id %}">
                          <i class="fa fa-trash-o fa-sm fa-fw mr-2 text-gray-400"></i>
                          &nbsp;Delete Course
                      </a>
                    </div>
                  </div>
              </td>
            </tr>
            {% endfor %}
            {% else %}
              <tr>
                  <td colspan="4" class="small">No courses has been added</td>
              </tr>
              {% endif %}
          </tbody>
      </table>
    </div>

</div>

{% endblock content %}

admins/templates/admins/duration.html
{% extends 'admins/base.html' %} {% block title %}Durations{% endblock title %} {% block content %}

<div class="container-fluid">
    <div class="card shadow  card-body p-2 ">
      <h5 class="pt-2 "><i class="fa fa-calendar fa-sm fa-fw mr-2 text-gray-400"></i>Duration</h5>
    </div>

     <a class="btn btn-primary btn-icon-split mt-4" role="button" href="{% url 'admins:add_duration' %}">
        <span class="text-white-50 icon">
            <i class="fas fa-plus fa-sm text-gray-400"></i>
        </span>
        <span class="text-white text small">Add Duration</span>
    </a>
    <a class="btn btn-secondary btn-icon-split mt-4" role="button" href="{% url 'admins:view_all_duration' %}">
        <span class="text-white-50 icon">
            <i class="fas fa-eye fa-sm text-gray-400"></i>
        </span>
        <span class="text-white text small">View all</span>
    </a>
    {% if messages %}
      {% for message in messages %}
        <div class="alert alert-dismissible {{ message.tags }} mt-3">
          <button type="button" class="close" data-dismiss="alert">
          ×
          </button>
          <strong>{{message}}</strong>
        </div>
     {% endfor %}
    {% endif %}

<div class="table-responsive mt-4">
      <table class="table table-sm table-bordered ">
          <thead>
            <tr class="bg-secondary text-white small">
                <th scope="col">SN</th>
                <th scope="col">Course code</th>
                <th scope="col">Course title</th>
                <th scope="col">Duration</th>
                <th scope="col text-align-right">Actions</th>
            </tr>
          </thead>
          <tbody>
          {% if durations %}
          {% for duration in durations %}
                <tr class="small">
                  <td scope="row">{{ forloop.counter }}</td>
                  <td scope="row">{{duration.course_id.code}}</td>
                  <td class="max-lines" scope="row">{{duration.course_id.course_title}}</td>

                        <td class="max-lines">
                         {{duration.duration_time}}
                       </td>
                        <td>
                            <div class="pull-right dropdown no-arrow justify-content-right">
                                <button
                                  class="btn btn-link btn-sm dropdown-toggle"
                                  aria-expanded="false"
                                  data-toggle="dropdown"
                                  type="button"
                                >
                                  <i class="fas fa-ellipsis-v "></i>
                                </button>
                                <div class="dropdown-menu shadow dropdown-menu-right animated--fade-in">
                                  <a class="dropdown-item btn-success" href="{% url 'admins:update_duration' id=duration.id %}">
                                      <i class="fa fa-edit fa-sm fa-fw mr-2 text-gray-400"></i>
                                      &nbsp;Edit Duration
                                  </a>
                                  <a class="dropdown-item" href="{% url 'admins:delete_duration' id=duration.id %}">
                                      <i class="fa fa-trash-o fa-sm fa-fw mr-2 text-gray-400"></i>
                                      &nbsp;Delete Duration
                                  </a>
                                </div>
                            </div>
                         </td>

               </tr>
            {% endfor %}
            {% else %}
              <tr>
                  <td colspan="4" class="small">No courses has been added</td>
              </tr>

              {% endif %}
          </tbody>
      </table>
    </div>
</div>

{% endblock content %}